// CFB Team Mappings for slugs to display names and ESPN IDs
export const CFB_TEAM_MAPPINGS: Record<string, { 
  name: string; 
  abbr: string; 
  espnAbbr: string;
  fullName: string;
}> = {
  "ucla-bruins": { name: "UCLA", abbr: "UCLA", espnAbbr: "26", fullName: "UCLA Bruins" },
  "arizona-wildcats": { name: "Arizona", abbr: "ARIZ", espnAbbr: "12", fullName: "Arizona Wildcats" },
  "arizona-st-sun-devils": { name: "Arizona State", abbr: "ASU", espnAbbr: "9", fullName: "Arizona State Sun Devils" },
  "utah-utes": { name: "Utah", abbr: "UTAH", espnAbbr: "254", fullName: "Utah Utes" },
  "colorado-buffaloes": { name: "Colorado", abbr: "COLO", espnAbbr: "38", fullName: "Colorado Buffaloes" },
  "usc-trojans": { name: "USC", abbr: "USC", espnAbbr: "30", fullName: "USC Trojans" },
  "oregon-ducks": { name: "Oregon", abbr: "ORE", espnAbbr: "2483", fullName: "Oregon Ducks" },
  "washington-huskies": { name: "Washington", abbr: "WASH", espnAbbr: "264", fullName: "Washington Huskies" },
  "ohio-st-buckeyes": { name: "Ohio State", abbr: "OSU", espnAbbr: "194", fullName: "Ohio State Buckeyes" },
  "michigan-wolverines": { name: "Michigan", abbr: "MICH", espnAbbr: "130", fullName: "Michigan Wolverines" },
  "penn-st-nittany-lions": { name: "Penn State", abbr: "PSU", espnAbbr: "213", fullName: "Penn State Nittany Lions" },
  "georgia-bulldogs": { name: "Georgia", abbr: "UGA", espnAbbr: "61", fullName: "Georgia Bulldogs" },
  "alabama-crimson-tide": { name: "Alabama", abbr: "ALA", espnAbbr: "333", fullName: "Alabama Crimson Tide" },
  "texas-longhorns": { name: "Texas", abbr: "TEX", espnAbbr: "251", fullName: "Texas Longhorns" },
  "oklahoma-sooners": { name: "Oklahoma", abbr: "OU", espnAbbr: "201", fullName: "Oklahoma Sooners" },
  "florida-gators": { name: "Florida", abbr: "FLA", espnAbbr: "57", fullName: "Florida Gators" },
  "lsu-tigers": { name: "LSU", abbr: "LSU", espnAbbr: "99", fullName: "LSU Tigers" },
  "clemson-tigers": { name: "Clemson", abbr: "CLEM", espnAbbr: "228", fullName: "Clemson Tigers" },
  "notre-dame-fighting-irish": { name: "Notre Dame", abbr: "ND", espnAbbr: "87", fullName: "Notre Dame Fighting Irish" },
  "florida-state-seminoles": { name: "Florida State", abbr: "FSU", espnAbbr: "52", fullName: "Florida State Seminoles" },
  "miami-fl-hurricanes": { name: "Miami", abbr: "MIA", espnAbbr: "2390", fullName: "Miami Hurricanes" },
  "virginia-tech-hokies": { name: "Virginia Tech", abbr: "VT", espnAbbr: "259", fullName: "Virginia Tech Hokies" },
  "north-carolina-tar-heels": { name: "North Carolina", abbr: "UNC", espnAbbr: "153", fullName: "North Carolina Tar Heels" },
  "wisconsin-badgers": { name: "Wisconsin", abbr: "WIS", espnAbbr: "275", fullName: "Wisconsin Badgers" },
  "iowa-hawkeyes": { name: "Iowa", abbr: "IOWA", espnAbbr: "2294", fullName: "Iowa Hawkeyes" },
  "iowa-st-cyclones": { name: "Iowa State", abbr: "ISU", espnAbbr: "66", fullName: "Iowa State Cyclones" },
  "nebraska-cornhuskers": { name: "Nebraska", abbr: "NEB", espnAbbr: "158", fullName: "Nebraska Cornhuskers" },
  "tennessee-volunteers": { name: "Tennessee", abbr: "TENN", espnAbbr: "2633", fullName: "Tennessee Volunteers" },
  "auburn-tigers": { name: "Auburn", abbr: "AUB", espnAbbr: "2", fullName: "Auburn Tigers" },
  "texas-am-aggies": { name: "Texas A&M", abbr: "TAMU", espnAbbr: "245", fullName: "Texas A&M Aggies" },
  "ole-miss-rebels": { name: "Ole Miss", abbr: "MISS", espnAbbr: "145", fullName: "Ole Miss Rebels" },
  "mississippi-state-bulldogs": { name: "Mississippi State", abbr: "MSST", espnAbbr: "344", fullName: "Mississippi State Bulldogs" },
  "arkansas-razorbacks": { name: "Arkansas", abbr: "ARK", espnAbbr: "8", fullName: "Arkansas Razorbacks" },
  "kentucky-wildcats": { name: "Kentucky", abbr: "UK", espnAbbr: "96", fullName: "Kentucky Wildcats" },
  "south-carolina-gamecocks": { name: "South Carolina", abbr: "SC", espnAbbr: "2579", fullName: "South Carolina Gamecocks" },
  "missouri-tigers": { name: "Missouri", abbr: "MIZ", espnAbbr: "142", fullName: "Missouri Tigers" },
  "vanderbilt-commodores": { name: "Vanderbilt", abbr: "VAN", espnAbbr: "238", fullName: "Vanderbilt Commodores" },
  "duke-blue-devils": { name: "Duke", abbr: "DUKE", espnAbbr: "150", fullName: "Duke Blue Devils" },
  "baylor-bears": { name: "Baylor", abbr: "BAY", espnAbbr: "239", fullName: "Baylor Bears" },
  "boston-college-eagles": { name: "Boston College", abbr: "BC", espnAbbr: "103", fullName: "Boston College Eagles" },
  "smu-mustangs": { name: "SMU", abbr: "SMU", espnAbbr: "2567", fullName: "SMU Mustangs" },
  "kansas-st-wildcats": { name: "Kansas State", abbr: "KSU", espnAbbr: "2306", fullName: "Kansas State Wildcats" },
  "indiana-hoosiers": { name: "Indiana", abbr: "IND", espnAbbr: "84", fullName: "Indiana Hoosiers" },
  "maryland-terrapins": { name: "Maryland", abbr: "MD", espnAbbr: "120", fullName: "Maryland Terrapins" },
  "rutgers-scarlet-knights": { name: "Rutgers", abbr: "RUT", espnAbbr: "164", fullName: "Rutgers Scarlet Knights" },
  "illinois-fighting-illini": { name: "Illinois", abbr: "ILL", espnAbbr: "356", fullName: "Illinois Fighting Illini" },
  "michigan-st-spartans": { name: "Michigan State", abbr: "MSU", espnAbbr: "127", fullName: "Michigan State Spartans" },
  "minnesota-golden-gophers": { name: "Minnesota", abbr: "MINN", espnAbbr: "135", fullName: "Minnesota Golden Gophers" },
  "boise-st-broncos": { name: "Boise State", abbr: "BSU", espnAbbr: "68", fullName: "Boise State Broncos" },
  "stanford-cardinal": { name: "Stanford", abbr: "STAN", espnAbbr: "24", fullName: "Stanford Cardinal" },
  "pittsburgh-panthers": { name: "Pittsburgh", abbr: "PITT", espnAbbr: "221", fullName: "Pittsburgh Panthers" },
  "syracuse-orange": { name: "Syracuse", abbr: "SYR", espnAbbr: "183", fullName: "Syracuse Orange" },
  "ucf-knights": { name: "UCF", abbr: "UCF", espnAbbr: "2116", fullName: "UCF Knights" },
  "houston-cougars": { name: "Houston", abbr: "HOU", espnAbbr: "248", fullName: "Houston Cougars" },
  "west-virginia-mountaineers": { name: "West Virginia", abbr: "WVU", espnAbbr: "277", fullName: "West Virginia Mountaineers" },
  "kansas-jayhawks": { name: "Kansas", abbr: "KU", espnAbbr: "2305", fullName: "Kansas Jayhawks" },
  "texas-tech-red-raiders": { name: "Texas Tech", abbr: "TTU", espnAbbr: "2641", fullName: "Texas Tech Red Raiders" },
  "louisville-cardinals": { name: "Louisville", abbr: "LOU", espnAbbr: "97", fullName: "Louisville Cardinals" },
  "tulane-green-wave": { name: "Tulane", abbr: "TUL", espnAbbr: "2655", fullName: "Tulane Green Wave" },
  "memphis-tigers": { name: "Memphis", abbr: "MEM", espnAbbr: "235", fullName: "Memphis Tigers" },
  "fresno-st-bulldogs": { name: "Fresno State", abbr: "FRES", espnAbbr: "278", fullName: "Fresno State Bulldogs" },
  "navy-midshipmen": { name: "Navy", abbr: "NAVY", espnAbbr: "2426", fullName: "Navy Midshipmen" },
  "army-black-nights": { name: "Army", abbr: "ARMY", espnAbbr: "349", fullName: "Army Black Knights" },
  "air-force-falcons": { name: "Air Force", abbr: "AF", espnAbbr: "2005", fullName: "Air Force Falcons" },
};
