// CFB Team Mappings - slug is the primary identifier
// Data source: VSiN team details dataset
export const CFB_TEAM_MAPPINGS: Record<string, { 
  name: string; 
  abbr: string; 
  espnAbbr: string;
  fullName: string;
}> = {
  // ACC
  "boston-college-eagles": { name: "Boston College", abbr: "BC", espnAbbr: "103", fullName: "boston college eagles" },
  "california-golden-bears": { name: "California", abbr: "CAL", espnAbbr: "25", fullName: "california golden bears" },
  "clemson-tigers": { name: "Clemson", abbr: "CLEM", espnAbbr: "228", fullName: "clemson tigers" },
  "duke-blue-devils": { name: "Duke", abbr: "DUKE", espnAbbr: "150", fullName: "duke blue devils" },
  "florida-state-seminoles": { name: "Florida State", abbr: "FSU", espnAbbr: "52", fullName: "florida state seminoles" },
  "florida-st-seminoles": { name: "Florida State", abbr: "FSU", espnAbbr: "52", fullName: "florida state seminoles" },
  "georgia-tech-yellow-jackets": { name: "Georgia Tech", abbr: "GT", espnAbbr: "59", fullName: "georgia tech yellow jackets" },
  "louisville-cardinals": { name: "Louisville", abbr: "LOU", espnAbbr: "97", fullName: "louisville cardinals" },
  "miami-hurricanes": { name: "Miami", abbr: "MIA", espnAbbr: "2390", fullName: "miami hurricanes" },
  "miami-fl-hurricanes": { name: "Miami", abbr: "MIA", espnAbbr: "2390", fullName: "miami hurricanes" },
  "nc-state-wolfpack": { name: "NC State", abbr: "NCST", espnAbbr: "152", fullName: "nc state wolfpack" },
  "north-carolina-tar-heels": { name: "North Carolina", abbr: "UNC", espnAbbr: "153", fullName: "north carolina tar heels" },
  "pittsburgh-panthers": { name: "Pittsburgh", abbr: "PITT", espnAbbr: "221", fullName: "pittsburgh panthers" },
  "smu-mustangs": { name: "SMU", abbr: "SMU", espnAbbr: "2567", fullName: "smu mustangs" },
  "stanford-cardinal": { name: "Stanford", abbr: "STAN", espnAbbr: "24", fullName: "stanford cardinal" },
  "syracuse-orange": { name: "Syracuse", abbr: "SYR", espnAbbr: "183", fullName: "syracuse orange" },
  "virginia-cavaliers": { name: "Virginia", abbr: "UVA", espnAbbr: "258", fullName: "virginia cavaliers" },
  "virginia-tech-hokies": { name: "Virginia Tech", abbr: "VT", espnAbbr: "259", fullName: "virginia tech hokies" },
  "wake-forest-demon-deacons": { name: "Wake Forest", abbr: "WAKE", espnAbbr: "154", fullName: "wake forest demon deacons" },

  // American
  "army-black-knights": { name: "Army", abbr: "ARMY", espnAbbr: "349", fullName: "army black knights" },
  "army-black-nights": { name: "Army", abbr: "ARMY", espnAbbr: "349", fullName: "army black knights" },
  "charlotte-49ers": { name: "Charlotte", abbr: "CLT", espnAbbr: "2429", fullName: "charlotte 49ers" },
  "east-carolina-pirates": { name: "East Carolina", abbr: "ECU", espnAbbr: "151", fullName: "east carolina pirates" },
  "florida-atlantic-owls": { name: "Florida Atlantic", abbr: "FAU", espnAbbr: "2226", fullName: "florida atlantic owls" },
  "fl-atlantic-owls": { name: "Florida Atlantic", abbr: "FAU", espnAbbr: "2226", fullName: "florida atlantic owls" },
  "memphis-tigers": { name: "Memphis", abbr: "MEM", espnAbbr: "235", fullName: "memphis tigers" },
  "navy-midshipmen": { name: "Navy", abbr: "NAVY", espnAbbr: "2426", fullName: "navy midshipmen" },
  "north-texas-mean-green": { name: "North Texas", abbr: "UNT", espnAbbr: "249", fullName: "north texas mean green" },
  "rice-owls": { name: "Rice", abbr: "RICE", espnAbbr: "242", fullName: "rice owls" },
  "south-florida-bulls": { name: "South Florida", abbr: "USF", espnAbbr: "58", fullName: "south florida bulls" },
  "temple-owls": { name: "Temple", abbr: "TEM", espnAbbr: "218", fullName: "temple owls" },
  "tulane-green-wave": { name: "Tulane", abbr: "TULN", espnAbbr: "2655", fullName: "tulane green wave" },
  "tulsa-golden-hurricane": { name: "Tulsa", abbr: "TLSA", espnAbbr: "202", fullName: "tulsa golden hurricane" },
  "uab-blazers": { name: "UAB", abbr: "UAB", espnAbbr: "5", fullName: "uab blazers" },
  "utsa-roadrunners": { name: "UTSA", abbr: "UTSA", espnAbbr: "2636", fullName: "utsa roadrunners" },
  "texas-san-antonio-roadrunners": { name: "UTSA", abbr: "UTSA", espnAbbr: "2636", fullName: "utsa roadrunners" },

  // Big 12
  "arizona-state-sun-devils": { name: "Arizona State", abbr: "ASU", espnAbbr: "9", fullName: "arizona state sun devils" },
  "arizona-wildcats": { name: "Arizona", abbr: "ARIZ", espnAbbr: "12", fullName: "arizona wildcats" },
  "byu-cougars": { name: "BYU", abbr: "BYU", espnAbbr: "252", fullName: "byu cougars" },
  "baylor-bears": { name: "Baylor", abbr: "BAY", espnAbbr: "239", fullName: "baylor bears" },
  "cincinnati-bearcats": { name: "Cincinnati", abbr: "CIN", espnAbbr: "2132", fullName: "cincinnati bearcats" },
  "colorado-buffaloes": { name: "Colorado", abbr: "COLO", espnAbbr: "38", fullName: "colorado buffaloes" },
  "houston-cougars": { name: "Houston", abbr: "HOU", espnAbbr: "248", fullName: "houston cougars" },
  "iowa-state-cyclones": { name: "Iowa State", abbr: "ISU", espnAbbr: "66", fullName: "iowa state cyclones" },
  "kansas-jayhawks": { name: "Kansas", abbr: "KU", espnAbbr: "2305", fullName: "kansas jayhawks" },
  "kansas-state-wildcats": { name: "Kansas State", abbr: "KSU", espnAbbr: "2306", fullName: "kansas state wildcats" },
  "oklahoma-state-cowboys": { name: "Oklahoma State", abbr: "OKST", espnAbbr: "197", fullName: "oklahoma state cowboys" },
  "tcu-horned-frogs": { name: "TCU", abbr: "TCU", espnAbbr: "2628", fullName: "tcu horned frogs" },
  "texas-tech-red-raiders": { name: "Texas Tech", abbr: "TTU", espnAbbr: "2641", fullName: "texas tech red raiders" },
  "ucf-knights": { name: "UCF", abbr: "UCF", espnAbbr: "2116", fullName: "ucf knights" },
  "utah-utes": { name: "Utah", abbr: "UTAH", espnAbbr: "254", fullName: "utah utes" },
  "west-virginia-mountaineers": { name: "West Virginia", abbr: "WVU", espnAbbr: "277", fullName: "west virginia mountaineers" },

  // Big Ten
  "illinois-fighting-illini": { name: "Illinois", abbr: "ILL", espnAbbr: "356", fullName: "illinois fighting illini" },
  "indiana-hoosiers": { name: "Indiana", abbr: "IND", espnAbbr: "84", fullName: "indiana hoosiers" },
  "iowa-hawkeyes": { name: "Iowa", abbr: "IOWA", espnAbbr: "2294", fullName: "iowa hawkeyes" },
  "iowa-hawkies": { name: "Iowa", abbr: "IOWA", espnAbbr: "2294", fullName: "iowa hawkeyes" },
  "maryland-terrapins": { name: "Maryland", abbr: "MD", espnAbbr: "120", fullName: "maryland terrapins" },
  "michigan-state-spartans": { name: "Michigan State", abbr: "MSU", espnAbbr: "127", fullName: "michigan state spartans" },
  "michigan-wolverines": { name: "Michigan", abbr: "MICH", espnAbbr: "130", fullName: "michigan wolverines" },
  "minnesota-golden-gophers": { name: "Minnesota", abbr: "MINN", espnAbbr: "135", fullName: "minnesota golden gophers" },
  "nebraska-cornhuskers": { name: "Nebraska", abbr: "NEB", espnAbbr: "158", fullName: "nebraska cornhuskers" },
  "northwestern-wildcats": { name: "Northwestern", abbr: "NU", espnAbbr: "77", fullName: "northwestern wildcats" },
  "ohio-state-buckeyes": { name: "Ohio State", abbr: "OSU", espnAbbr: "194", fullName: "ohio state buckeyes" },
  "ohio-st-buckeyes": { name: "Ohio State", abbr: "OSU", espnAbbr: "194", fullName: "ohio state buckeyes" },
  "oregon-ducks": { name: "Oregon", abbr: "ORE", espnAbbr: "2483", fullName: "oregon ducks" },
  "penn-state-nittany-lions": { name: "Penn State", abbr: "PSU", espnAbbr: "213", fullName: "penn state nittany lions" },
  "penn-st-nittany-lions": { name: "Penn State", abbr: "PSU", espnAbbr: "213", fullName: "penn state nittany lions" },
  "purdue-boilermakers": { name: "Purdue", abbr: "PUR", espnAbbr: "2509", fullName: "purdue boilermakers" },
  "rutgers-scarlet-knights": { name: "Rutgers", abbr: "RUTG", espnAbbr: "164", fullName: "rutgers scarlet knights" },
  "ucla-bruins": { name: "UCLA", abbr: "UCLA", espnAbbr: "26", fullName: "ucla bruins" },
  "usc-trojans": { name: "USC", abbr: "USC", espnAbbr: "30", fullName: "usc trojans" },
  "washington-huskies": { name: "Washington", abbr: "WASH", espnAbbr: "264", fullName: "washington huskies" },
  "wisconsin-badgers": { name: "Wisconsin", abbr: "WISC", espnAbbr: "275", fullName: "wisconsin badgers" },

  // Conference USA
  "delaware-blue-hens": { name: "Delaware", abbr: "DEL", espnAbbr: "48", fullName: "delaware blue hens" },
  "delaware": { name: "Delaware", abbr: "DEL", espnAbbr: "48", fullName: "delaware blue hens" },
  "florida-international-panthers": { name: "FIU", abbr: "FIU", espnAbbr: "2229", fullName: "florida international panthers" },
  "florida-intl-golden-panthers": { name: "FIU", abbr: "FIU", espnAbbr: "2229", fullName: "florida international panthers" },
  "jacksonville-state-gamecocks": { name: "Jacksonville State", abbr: "JAXST", espnAbbr: "55", fullName: "jacksonville state gamecocks" },
  "jacksonville-st": { name: "Jacksonville State", abbr: "JAXST", espnAbbr: "55", fullName: "jacksonville state gamecocks" },
  "kennesaw-state-owls": { name: "Kennesaw State", abbr: "KENN", espnAbbr: "338", fullName: "kennesaw state owls" },
  "kennesaw-st": { name: "Kennesaw State", abbr: "KENN", espnAbbr: "338", fullName: "kennesaw state owls" },
  "liberty-flames": { name: "Liberty", abbr: "LIB", espnAbbr: "2335", fullName: "liberty flames" },
  "louisiana-tech-bulldogs": { name: "Louisiana Tech", abbr: "LT", espnAbbr: "2348", fullName: "louisiana tech bulldogs" },
  "middle-tennessee-blue-raiders": { name: "Middle Tennessee", abbr: "MTSU", espnAbbr: "2393", fullName: "middle tennessee blue raiders" },
  "middle-tenn-st-blue-raiders": { name: "Middle Tennessee", abbr: "MTSU", espnAbbr: "2393", fullName: "middle tennessee blue raiders" },
  "missouri-state-bears": { name: "Missouri State", abbr: "MOST", espnAbbr: "2623", fullName: "missouri state bears" },
  "missouri-st": { name: "Missouri State", abbr: "MOST", espnAbbr: "2623", fullName: "missouri state bears" },
  "new-mexico-state-aggies": { name: "New Mexico State", abbr: "NMSU", espnAbbr: "166", fullName: "new mexico state aggies" },
  "new-mexico-st-aggies": { name: "New Mexico State", abbr: "NMSU", espnAbbr: "166", fullName: "new mexico state aggies" },
  "sam-houston-bearkats": { name: "Sam Houston", abbr: "SHSU", espnAbbr: "2534", fullName: "sam houston bearkats" },
  "utep-miners": { name: "UTEP", abbr: "UTEP", espnAbbr: "2638", fullName: "utep miners" },
  "western-kentucky-hilltoppers": { name: "Western Kentucky", abbr: "WKU", espnAbbr: "98", fullName: "western kentucky hilltoppers" },

  // FBS Independents
  "notre-dame-fighting-irish": { name: "Notre Dame", abbr: "ND", espnAbbr: "87", fullName: "notre dame fighting irish" },
  "uconn-huskies": { name: "UConn", abbr: "UCONN", espnAbbr: "41", fullName: "uconn huskies" },
  "connecticut-huskies": { name: "UConn", abbr: "UCONN", espnAbbr: "41", fullName: "uconn huskies" },

  // MAC
  "akron-zips": { name: "Akron", abbr: "AKR", espnAbbr: "2006", fullName: "akron zips" },
  "ball-state-cardinals": { name: "Ball State", abbr: "BALL", espnAbbr: "2050", fullName: "ball state cardinals" },
  "ball-st-cardinals": { name: "Ball State", abbr: "BALL", espnAbbr: "2050", fullName: "ball state cardinals" },
  "bowling-green-falcons": { name: "Bowling Green", abbr: "BGSU", espnAbbr: "189", fullName: "bowling green falcons" },
  "buffalo-bulls": { name: "Buffalo", abbr: "BUF", espnAbbr: "2084", fullName: "buffalo bulls" },
  "central-michigan-chippewas": { name: "Central Michigan", abbr: "CMU", espnAbbr: "2117", fullName: "central michigan chippewas" },
  "eastern-michigan-eagles": { name: "Eastern Michigan", abbr: "EMU", espnAbbr: "2199", fullName: "eastern michigan eagles" },
  "e-michigan-eagles": { name: "Eastern Michigan", abbr: "EMU", espnAbbr: "2199", fullName: "eastern michigan eagles" },
  "kent-state-golden-flashes": { name: "Kent State", abbr: "KENT", espnAbbr: "2309", fullName: "kent state golden flashes" },
  "kent-st-golden-flashes": { name: "Kent State", abbr: "KENT", espnAbbr: "2309", fullName: "kent state golden flashes" },
  "massachusetts-minutemen": { name: "UMass", abbr: "UMASS", espnAbbr: "113", fullName: "massachusetts minutemen" },
  "miami-oh-redhawks": { name: "Miami (OH)", abbr: "M-OH", espnAbbr: "193", fullName: "miami oh redhawks" },
  "northern-illinois-huskies": { name: "Northern Illinois", abbr: "NIU", espnAbbr: "2459", fullName: "northern illinois huskies" },
  "n-illinois-huskies": { name: "Northern Illinois", abbr: "NIU", espnAbbr: "2459", fullName: "northern illinois huskies" },
  "ohio-bobcats": { name: "Ohio", abbr: "OHIO", espnAbbr: "195", fullName: "ohio bobcats" },
  "toledo-rockets": { name: "Toledo", abbr: "TOL", espnAbbr: "2649", fullName: "toledo rockets" },
  "western-michigan-broncos": { name: "Western Michigan", abbr: "WMU", espnAbbr: "2711", fullName: "western michigan broncos" },

  // Mountain West
  "air-force-falcons": { name: "Air Force", abbr: "AF", espnAbbr: "2005", fullName: "air force falcons" },
  "boise-state-broncos": { name: "Boise State", abbr: "BSU", espnAbbr: "68", fullName: "boise state broncos" },
  "colorado-state-rams": { name: "Colorado State", abbr: "CSU", espnAbbr: "36", fullName: "colorado state rams" },
  "fresno-state-bulldogs": { name: "Fresno State", abbr: "FRES", espnAbbr: "278", fullName: "fresno state bulldogs" },
  "hawaii-rainbow-warriors": { name: "Hawaii", abbr: "HAW", espnAbbr: "62", fullName: "hawaii rainbow warriors" },
  "nevada-wolf-pack": { name: "Nevada", abbr: "NEV", espnAbbr: "2440", fullName: "nevada wolf pack" },
  "new-mexico-lobos": { name: "New Mexico", abbr: "UNM", espnAbbr: "167", fullName: "new mexico lobos" },
  "san-diego-state-aztecs": { name: "San Diego State", abbr: "SDSU", espnAbbr: "21", fullName: "san diego state aztecs" },
  "san-jose-state-spartans": { name: "San Jose State", abbr: "SJSU", espnAbbr: "23", fullName: "san jose state spartans" },
  "san-jose-st-spartans": { name: "San Jose State", abbr: "SJSU", espnAbbr: "23", fullName: "san jose state spartans" },
  "unlv-rebels": { name: "UNLV", abbr: "UNLV", espnAbbr: "2439", fullName: "unlv rebels" },
  "utah-state-aggies": { name: "Utah State", abbr: "USU", espnAbbr: "328", fullName: "utah state aggies" },
  "wyoming-cowboys": { name: "Wyoming", abbr: "WYO", espnAbbr: "2751", fullName: "wyoming cowboys" },

  // Pac-12
  "oregon-state-beavers": { name: "Oregon State", abbr: "ORST", espnAbbr: "204", fullName: "oregon state beavers" },
  "washington-state-cougars": { name: "Washington State", abbr: "WAZZU", espnAbbr: "265", fullName: "washington state cougars" },

  // SEC
  "alabama-crimson-tide": { name: "Alabama", abbr: "ALA", espnAbbr: "333", fullName: "alabama crimson tide" },
  "arkansas-razorbacks": { name: "Arkansas", abbr: "ARK", espnAbbr: "8", fullName: "arkansas razorbacks" },
  "auburn-tigers": { name: "Auburn", abbr: "AUB", espnAbbr: "2", fullName: "auburn tigers" },
  "florida-gators": { name: "Florida", abbr: "FLA", espnAbbr: "57", fullName: "florida gators" },
  "georgia-bulldogs": { name: "Georgia", abbr: "UGA", espnAbbr: "61", fullName: "georgia bulldogs" },
  "kentucky-wildcats": { name: "Kentucky", abbr: "UK", espnAbbr: "96", fullName: "kentucky wildcats" },
  "lsu-tigers": { name: "LSU", abbr: "LSU", espnAbbr: "99", fullName: "lsu tigers" },
  "mississippi-state-bulldogs": { name: "Mississippi State", abbr: "MSST", espnAbbr: "344", fullName: "mississippi state bulldogs" },
  "mississippi-st-bulldogs": { name: "Mississippi State", abbr: "MSST", espnAbbr: "344", fullName: "mississippi state bulldogs" },
  "missouri-tigers": { name: "Missouri", abbr: "MIZZOU", espnAbbr: "142", fullName: "missouri tigers" },
  "oklahoma-sooners": { name: "Oklahoma", abbr: "OU", espnAbbr: "201", fullName: "oklahoma sooners" },
  "ole-miss-rebels": { name: "Ole Miss", abbr: "MISS", espnAbbr: "145", fullName: "ole miss rebels" },
  "south-carolina-gamecocks": { name: "South Carolina", abbr: "SC", espnAbbr: "2579", fullName: "south carolina gamecocks" },
  "tennessee-volunteers": { name: "Tennessee", abbr: "TENN", espnAbbr: "2633", fullName: "tennessee volunteers" },
  "texas-am-aggies": { name: "Texas A&M", abbr: "TAMU", espnAbbr: "245", fullName: "texas am aggies" },
  "texas-a-and-m-aggies": { name: "Texas A&M", abbr: "TAMU", espnAbbr: "245", fullName: "texas am aggies" },
  "texas-longhorns": { name: "Texas", abbr: "TEX", espnAbbr: "251", fullName: "texas longhorns" },
  "vanderbilt-commodores": { name: "Vanderbilt", abbr: "VAN", espnAbbr: "238", fullName: "vanderbilt commodores" },

  // Sun Belt
  "app-state-mountaineers": { name: "App State", abbr: "APP", espnAbbr: "2026", fullName: "app state mountaineers" },
  "appalachian-st-mountaineers": { name: "App State", abbr: "APP", espnAbbr: "2026", fullName: "app state mountaineers" },
  "arkansas-state-red-wolves": { name: "Arkansas State", abbr: "ARST", espnAbbr: "2032", fullName: "arkansas state red wolves" },
  "arkansas-st-red-wolves": { name: "Arkansas State", abbr: "ARST", espnAbbr: "2032", fullName: "arkansas state red wolves" },
  "coastal-carolina-chanticleers": { name: "Coastal Carolina", abbr: "CCU", espnAbbr: "324", fullName: "coastal carolina chanticleers" },
  "georgia-southern-eagles": { name: "Georgia Southern", abbr: "GASO", espnAbbr: "290", fullName: "georgia southern eagles" },
  "georgia-state-panthers": { name: "Georgia State", abbr: "GAST", espnAbbr: "2247", fullName: "georgia state panthers" },
  "georgia-st-panthers": { name: "Georgia State", abbr: "GAST", espnAbbr: "2247", fullName: "georgia state panthers" },
  "james-madison-dukes": { name: "James Madison", abbr: "JMU", espnAbbr: "256", fullName: "james madison dukes" },
  "james-madison": { name: "James Madison", abbr: "JMU", espnAbbr: "256", fullName: "james madison dukes" },
  "louisiana-ragin-cajuns": { name: "Louisiana", abbr: "ULL", espnAbbr: "309", fullName: "louisiana ragin cajuns" },
  "marshall-thundering-herd": { name: "Marshall", abbr: "MRSH", espnAbbr: "276", fullName: "marshall thundering herd" },
  "old-dominion-monarchs": { name: "Old Dominion", abbr: "ODU", espnAbbr: "295", fullName: "old dominion monarchs" },
  "south-alabama-jaguars": { name: "South Alabama", abbr: "USA", espnAbbr: "6", fullName: "south alabama jaguars" },
  "southern-miss-golden-eagles": { name: "Southern Miss", abbr: "SO MISS", espnAbbr: "2572", fullName: "southern miss golden eagles" },
  "southern-miss": { name: "Southern Miss", abbr: "SO MISS", espnAbbr: "2572", fullName: "southern miss golden eagles" },
  "texas-state-bobcats": { name: "Texas State", abbr: "TXST", espnAbbr: "326", fullName: "texas state bobcats" },
  "texas-st-bobcats": { name: "Texas State", abbr: "TXST", espnAbbr: "326", fullName: "texas state bobcats" },
  "troy-trojans": { name: "Troy", abbr: "TROY", espnAbbr: "2653", fullName: "troy trojans" },
  "ul-monroe-warhawks": { name: "UL Monroe", abbr: "ULM", espnAbbr: "2433", fullName: "ul monroe warhawks" },
};
