// CFB Team Mappings for slugs to display names and ESPN IDs
export const CFB_TEAM_MAPPINGS: Record<string, { 
  name: string; 
  abbr: string; 
  espnAbbr: string;
  fullName: string;
}> = {
  "ucla-bruins": { name: "UCLA", abbr: "UCLA", espnAbbr: "26", fullName: "UCLA Bruins" },
  "arizona-wildcats": { name: "Arizona", abbr: "ARIZ", espnAbbr: "12", fullName: "Arizona Wildcats" },
  "arizona-st-sun-devils": { name: "Arizona State", abbr: "ASU", espnAbbr: "9", fullName: "Arizona State Sun Devils" },
  "utah-utes": { name: "Utah", abbr: "UTAH", espnAbbr: "254", fullName: "Utah Utes" },
  "colorado-buffaloes": { name: "Colorado", abbr: "COLO", espnAbbr: "38", fullName: "Colorado Buffaloes" },
  "usc-trojans": { name: "USC", abbr: "USC", espnAbbr: "30", fullName: "USC Trojans" },
  "oregon-ducks": { name: "Oregon", abbr: "ORE", espnAbbr: "2483", fullName: "Oregon Ducks" },
  "washington-huskies": { name: "Washington", abbr: "WASH", espnAbbr: "264", fullName: "Washington Huskies" },
  "ohio-st-buckeyes": { name: "Ohio State", abbr: "OSU", espnAbbr: "194", fullName: "Ohio State Buckeyes" },
  "michigan-wolverines": { name: "Michigan", abbr: "MICH", espnAbbr: "130", fullName: "Michigan Wolverines" },
  "penn-st-nittany-lions": { name: "Penn State", abbr: "PSU", espnAbbr: "213", fullName: "Penn State Nittany Lions" },
  "georgia-bulldogs": { name: "Georgia", abbr: "UGA", espnAbbr: "61", fullName: "Georgia Bulldogs" },
  "alabama-crimson-tide": { name: "Alabama", abbr: "ALA", espnAbbr: "333", fullName: "Alabama Crimson Tide" },
  "texas-longhorns": { name: "Texas", abbr: "TEX", espnAbbr: "251", fullName: "Texas Longhorns" },
  "oklahoma-sooners": { name: "Oklahoma", abbr: "OU", espnAbbr: "201", fullName: "Oklahoma Sooners" },
  "florida-gators": { name: "Florida", abbr: "FLA", espnAbbr: "57", fullName: "Florida Gators" },
  "lsu-tigers": { name: "LSU", abbr: "LSU", espnAbbr: "99", fullName: "LSU Tigers" },
  "clemson-tigers": { name: "Clemson", abbr: "CLEM", espnAbbr: "228", fullName: "Clemson Tigers" },
  "notre-dame-fighting-irish": { name: "Notre Dame", abbr: "ND", espnAbbr: "87", fullName: "Notre Dame Fighting Irish" },
  "florida-state-seminoles": { name: "Florida State", abbr: "FSU", espnAbbr: "52", fullName: "Florida State Seminoles" },
  "miami-fl-hurricanes": { name: "Miami", abbr: "MIA", espnAbbr: "2390", fullName: "Miami Hurricanes" },
  "virginia-tech-hokies": { name: "Virginia Tech", abbr: "VT", espnAbbr: "259", fullName: "Virginia Tech Hokies" },
  "north-carolina-tar-heels": { name: "North Carolina", abbr: "UNC", espnAbbr: "153", fullName: "North Carolina Tar Heels" },
  "wisconsin-badgers": { name: "Wisconsin", abbr: "WIS", espnAbbr: "275", fullName: "Wisconsin Badgers" },
  "iowa-hawkeyes": { name: "Iowa", abbr: "IOWA", espnAbbr: "2294", fullName: "Iowa Hawkeyes" },
  "iowa-st-cyclones": { name: "Iowa State", abbr: "ISU", espnAbbr: "66", fullName: "Iowa State Cyclones" },
  "nebraska-cornhuskers": { name: "Nebraska", abbr: "NEB", espnAbbr: "158", fullName: "Nebraska Cornhuskers" },
  "tennessee-volunteers": { name: "Tennessee", abbr: "TENN", espnAbbr: "2633", fullName: "Tennessee Volunteers" },
  "auburn-tigers": { name: "Auburn", abbr: "AUB", espnAbbr: "2", fullName: "Auburn Tigers" },
  "texas-am-aggies": { name: "Texas A&M", abbr: "TAMU", espnAbbr: "245", fullName: "Texas A&M Aggies" },
  "ole-miss-rebels": { name: "Ole Miss", abbr: "MISS", espnAbbr: "145", fullName: "Ole Miss Rebels" },
  "mississippi-state-bulldogs": { name: "Mississippi State", abbr: "MSST", espnAbbr: "344", fullName: "Mississippi State Bulldogs" },
  "arkansas-razorbacks": { name: "Arkansas", abbr: "ARK", espnAbbr: "8", fullName: "Arkansas Razorbacks" },
  "kentucky-wildcats": { name: "Kentucky", abbr: "UK", espnAbbr: "96", fullName: "Kentucky Wildcats" },
  "south-carolina-gamecocks": { name: "South Carolina", abbr: "SC", espnAbbr: "2579", fullName: "South Carolina Gamecocks" },
  "missouri-tigers": { name: "Missouri", abbr: "MIZ", espnAbbr: "142", fullName: "Missouri Tigers" },
  "vanderbilt-commodores": { name: "Vanderbilt", abbr: "VAN", espnAbbr: "238", fullName: "Vanderbilt Commodores" },
  "duke-blue-devils": { name: "Duke", abbr: "DUKE", espnAbbr: "150", fullName: "Duke Blue Devils" },
  "baylor-bears": { name: "Baylor", abbr: "BAY", espnAbbr: "239", fullName: "Baylor Bears" },
  "boston-college-eagles": { name: "Boston College", abbr: "BC", espnAbbr: "103", fullName: "Boston College Eagles" },
  "smu-mustangs": { name: "SMU", abbr: "SMU", espnAbbr: "2567", fullName: "SMU Mustangs" },
  "kansas-st-wildcats": { name: "Kansas State", abbr: "KSU", espnAbbr: "2306", fullName: "Kansas State Wildcats" },
  "indiana-hoosiers": { name: "Indiana", abbr: "IND", espnAbbr: "84", fullName: "Indiana Hoosiers" },
  "maryland-terrapins": { name: "Maryland", abbr: "MD", espnAbbr: "120", fullName: "Maryland Terrapins" },
  "rutgers-scarlet-knights": { name: "Rutgers", abbr: "RUT", espnAbbr: "164", fullName: "Rutgers Scarlet Knights" },
  "illinois-fighting-illini": { name: "Illinois", abbr: "ILL", espnAbbr: "356", fullName: "Illinois Fighting Illini" },
  "michigan-st-spartans": { name: "Michigan State", abbr: "MSU", espnAbbr: "127", fullName: "Michigan State Spartans" },
  "minnesota-golden-gophers": { name: "Minnesota", abbr: "MINN", espnAbbr: "135", fullName: "Minnesota Golden Gophers" },
  "boise-st-broncos": { name: "Boise State", abbr: "BSU", espnAbbr: "68", fullName: "Boise State Broncos" },
  "stanford-cardinal": { name: "Stanford", abbr: "STAN", espnAbbr: "24", fullName: "Stanford Cardinal" },
  "pittsburgh-panthers": { name: "Pittsburgh", abbr: "PITT", espnAbbr: "221", fullName: "Pittsburgh Panthers" },
  "syracuse-orange": { name: "Syracuse", abbr: "SYR", espnAbbr: "183", fullName: "Syracuse Orange" },
  "ucf-knights": { name: "UCF", abbr: "UCF", espnAbbr: "2116", fullName: "UCF Knights" },
  "houston-cougars": { name: "Houston", abbr: "HOU", espnAbbr: "248", fullName: "Houston Cougars" },
  "west-virginia-mountaineers": { name: "West Virginia", abbr: "WVU", espnAbbr: "277", fullName: "West Virginia Mountaineers" },
  "kansas-jayhawks": { name: "Kansas", abbr: "KU", espnAbbr: "2305", fullName: "Kansas Jayhawks" },
  "texas-tech-red-raiders": { name: "Texas Tech", abbr: "TTU", espnAbbr: "2641", fullName: "Texas Tech Red Raiders" },
  "louisville-cardinals": { name: "Louisville", abbr: "LOU", espnAbbr: "97", fullName: "Louisville Cardinals" },
  "tulane-green-wave": { name: "Tulane", abbr: "TUL", espnAbbr: "2655", fullName: "Tulane Green Wave" },
  "memphis-tigers": { name: "Memphis", abbr: "MEM", espnAbbr: "235", fullName: "Memphis Tigers" },
  "fresno-st-bulldogs": { name: "Fresno State", abbr: "FRES", espnAbbr: "278", fullName: "Fresno State Bulldogs" },
  "navy-midshipmen": { name: "Navy", abbr: "NAVY", espnAbbr: "2426", fullName: "Navy Midshipmen" },
  "army-black-nights": { name: "Army", abbr: "ARMY", espnAbbr: "349", fullName: "Army Black Knights" },
  "air-force-falcons": { name: "Air Force", abbr: "AF", espnAbbr: "2005", fullName: "Air Force Falcons" },
  "marshall-thundering-herd": { name: "Marshall", abbr: "MAR", espnAbbr: "276", fullName: "Marshall Thundering Herd" },
  "coastal-carolina-chanticleers": { name: "Coastal Carolina", abbr: "CCU", espnAbbr: "324", fullName: "Coastal Carolina Chanticleers" },
  "texas-san-antonio-roadrunners": { name: "UTSA", abbr: "UTSA", espnAbbr: "2636", fullName: "UTSA Roadrunners" },
  "rice-owls": { name: "Rice", abbr: "RICE", espnAbbr: "242", fullName: "Rice Owls" },
  "sam-houston-st-bearkats": { name: "Sam Houston State", abbr: "SHSU", espnAbbr: "2529", fullName: "Sam Houston State Bearkats" },
  "louisiana-tech-bulldogs": { name: "Louisiana Tech", abbr: "LT", espnAbbr: "2348", fullName: "Louisiana Tech Bulldogs" },
  "buffalo-bulls": { name: "Buffalo", abbr: "BUFF", espnAbbr: "2084", fullName: "Buffalo Bulls" },
  "bowling-green-falcons": { name: "Bowling Green", abbr: "BGSU", espnAbbr: "189", fullName: "Bowling Green Falcons" },
  "connecticut-huskies": { name: "Connecticut", abbr: "CONN", espnAbbr: "41", fullName: "Connecticut Huskies" },
  "uab-blazers": { name: "UAB", abbr: "UAB", espnAbbr: "5", fullName: "UAB Blazers" },
  "north-texas-mean-green": { name: "North Texas", abbr: "UNT", espnAbbr: "249", fullName: "North Texas Mean Green" },
  "east-carolina-pirates": { name: "East Carolina", abbr: "ECU", espnAbbr: "151", fullName: "East Carolina Pirates" },
  "temple-owls": { name: "Temple", abbr: "TEM", espnAbbr: "218", fullName: "Temple Owls" },
  "new-mexico-lobos": { name: "New Mexico", abbr: "UNM", espnAbbr: "167", fullName: "New Mexico Lobos" },
  "unlv-rebels": { name: "UNLV", abbr: "UNLV", espnAbbr: "2439", fullName: "UNLV Rebels" },
  "louisiana-ragin-cajuns": { name: "Louisiana", abbr: "ULL", espnAbbr: "309", fullName: "Louisiana Ragin' Cajuns" },
  "s-alabama-jaguars": { name: "South Alabama", abbr: "USA", espnAbbr: "6", fullName: "South Alabama Jaguars" },
  "delaware": { name: "Delaware", abbr: "DEL", espnAbbr: "48", fullName: "Delaware Fightin' Blue Hens" },
  "liberty-flames": { name: "Liberty", abbr: "LIB", espnAbbr: "2335", fullName: "Liberty Flames" },
  "new-mexico-st-aggies": { name: "New Mexico State", abbr: "NMSU", espnAbbr: "166", fullName: "New Mexico State Aggies" },
  "w-kentucky-hilltoppers": { name: "Western Kentucky", abbr: "WKU", espnAbbr: "98", fullName: "Western Kentucky Hilltoppers" },
  "virginia-cavaliers": { name: "Virginia", abbr: "UVA", espnAbbr: "258", fullName: "Virginia Cavaliers" },
  "california-golden-bears": { name: "California", abbr: "CAL", espnAbbr: "25", fullName: "California Golden Bears" },
  "c-michigan-chippewas": { name: "Central Michigan", abbr: "CMU", espnAbbr: "2117", fullName: "Central Michigan Chippewas" },
  "w-michigan-broncos": { name: "Western Michigan", abbr: "WMU", espnAbbr: "2711", fullName: "Western Michigan Broncos" },
  "oklahoma-st-cowboys": { name: "Oklahoma State", abbr: "OKST", espnAbbr: "197", fullName: "Oklahoma State Cowboys" },
  "purdue-boilermakers": { name: "Purdue", abbr: "PUR", espnAbbr: "2509", fullName: "Purdue Boilermakers" },
  "wyoming-cowboys": { name: "Wyoming", abbr: "WYO", espnAbbr: "2751", fullName: "Wyoming Cowboys" },
  "san-diego-st-aztecs": { name: "San Diego State", abbr: "SDSU", espnAbbr: "21", fullName: "San Diego State Aztecs" },
  "wake-forest-demon-deacons": { name: "Wake Forest", abbr: "WAKE", espnAbbr: "154", fullName: "Wake Forest Demon Deacons" },
  "georgia-tech-yellow-jackets": { name: "Georgia Tech", abbr: "GT", espnAbbr: "59", fullName: "Georgia Tech Yellow Jackets" },
  "nc-state-wolfpack": { name: "NC State", abbr: "NCST", espnAbbr: "152", fullName: "NC State Wolfpack" },
  "washington-st-cougars": { name: "Washington State", abbr: "WSU", espnAbbr: "265", fullName: "Washington State Cougars" },
  "oregon-st-beavers": { name: "Oregon State", abbr: "OSU", espnAbbr: "204", fullName: "Oregon State Beavers" },
  "arkansas-st-red-wolves": { name: "Arkansas State", abbr: "ARST", espnAbbr: "2032", fullName: "Arkansas State Red Wolves" },
  "troy-trojans": { name: "Troy", abbr: "TROY", espnAbbr: "2653", fullName: "Troy Trojans" },
  "cincinnati-bearcats": { name: "Cincinnati", abbr: "CIN", espnAbbr: "2132", fullName: "Cincinnati Bearcats" },
  "hawaii-rainbow-warriors": { name: "Hawaii", abbr: "HAW", espnAbbr: "62", fullName: "Hawaii Rainbow Warriors" },
  "san-jose-st-spartans": { name: "San Jose State", abbr: "SJSU", espnAbbr: "23", fullName: "San Jose State Spartans" },
  "miami-oh-redhawks": { name: "Miami (OH)", abbr: "MIAMI", espnAbbr: "193", fullName: "Miami (OH) RedHawks" },
  "ohio-bobcats": { name: "Ohio", abbr: "OHIO", espnAbbr: "195", fullName: "Ohio Bobcats" },
  "byu-cougars": { name: "BYU", abbr: "BYU", espnAbbr: "252", fullName: "BYU Cougars" },
  "texas-a-and-m-aggies": { name: "Texas A&M", abbr: "TAMU", espnAbbr: "245", fullName: "Texas A&M Aggies" },
  "tcu-horned-frogs": { name: "TCU", abbr: "TCU", espnAbbr: "2628", fullName: "TCU Horned Frogs" },
  "norfolk-st": { name: "Norfolk State", abbr: "NSU", espnAbbr: "2450", fullName: "Norfolk State Spartans" },
  "delaware-st": { name: "Delaware State", abbr: "DSU", espnAbbr: "47", fullName: "Delaware State Hornets" },
  "old-dominion-monarchs": { name: "Old Dominion", abbr: "ODU", espnAbbr: "295", fullName: "Old Dominion Monarchs" },
  "la-monroe-warhawks": { name: "Louisiana Monroe", abbr: "ULM", espnAbbr: "2433", fullName: "Louisiana Monroe Warhawks" },
  // Additional slug variations
  "mississippi": { name: "Mississippi State", abbr: "MSST", espnAbbr: "344", fullName: "Mississippi State Bulldogs" },
  "ole-miss": { name: "Ole Miss", abbr: "MISS", espnAbbr: "145", fullName: "Ole Miss Rebels" },
};
